replicaCount: 1

image:
  repository: adenli/fms-ui
  tag: dev-latest
  pullPolicy: IfNotPresent

containerPort: 3000

service:
  type: LoadBalancer
  port: 3000

env:
  REACT_APP_ENV: dev
  REACT_APP_GATEWAY_URL: "http://gatewayservice-gateway-dev:8080"
